backend:
  name: github
  repo: hyde-staging/decap-test

site_url: https://hyde-staging.github.io/decap-test
logo_url: /admin/assets/logo.svg

media_folder: "_media"
public_folder: "media"

commit_messages:
  create: Create {{collection}} "{{slug}}" from Decap
  update: Update {{collection}} "{{slug}}" from Decap
  delete: Delete {{collection}} "{{slug}}" from Decap
  uploadMedia: Upload "{{path}}" from Decap
  deleteMedia: Delete "{{path}}" from Decap
  openAuthoring: '{{message}}'

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    description: "Blog posts to be displayed on the site"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    preview_path: posts/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Description", name: "Description", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
